# Generated by Django 2.2.5 on 2020-01-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=600)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('price', models.IntegerField()),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('bedsitter', 'Bedsitter'), ('1 bedroom', '1 Bedroom'), ('custom', 'Custom')], default='Single', max_length=100)),
                ('image', models.ImageField(null=True, upload_to='images/room/images/')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
