# Generated by Django 2.2.5 on 2020-01-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0002_room_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='highlighted',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
