# Generated by Django 2.2.5 on 2020-01-12 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0003_room_highlighted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='highlighted',
            new_name='highlight',
        ),
    ]
