# Generated by Django 2.2.5 on 2020-01-12 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0004_auto_20200112_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='highlight',
            new_name='highlighted',
        ),
    ]
