# Generated by Django 2.2.5 on 2020-01-12 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0005_auto_20200112_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='highlighted',
            new_name='highlight',
        ),
    ]
