# Generated by Django 2.2.5 on 2020-01-12 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0006_auto_20200112_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='highlight',
            new_name='highlighted',
        ),
    ]
