# Generated by Django 2.2.5 on 2020-01-12 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0007_auto_20200112_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='highlighted',
        ),
    ]
